### ISSUE TITLE
Timouts are not cleared on destroy causing type errors

### ISSUE THREAD

**Issue by vendi95** [nhn/tui.editor#2236]
## Describe the bug
Timers are not properly cleared in multiple destroy functions throughout the code which causes exceptions when the timed functions run on the destroyed editor instance.

Two examples:

1. ScrollSync timer not removed:

https://github.com/nhn/tui.editor/blob/3983510e871bf4cfdd98131a45e447d8cad1fd86/apps/editor/src/markdown/scroll/scrollSync.ts#L70-L72

Might result in:
```
TypeError: Cannot read properties of null (reading 'nearestDesc')
    at posFromCaret (http://localhost:4200/webpack:/node_modules/prosemirror-view/dist/index.es.js:325:29)
    at posAtCoords (http://localhost:4200/webpack:/node_modules/prosemirror-view/dist/index.es.js:408:15)
    at EditorView.posAtCoords (http://localhost:4200/webpack:/node_modules/prosemirror-view/dist/index.es.js:5134:10)
    at ScrollSync.syncPreviewScrollTop (http://localhost:4200/webpack:/node_modules/@toast-ui/editor/dist/esm/index.js:21889:34)
    at apply (http://localhost:4200/webpack:/node_modules/@toast-ui/editor/dist/esm/index.js:21850:23)
```

2. EditorBase.focus timer not removed:
https://github.com/nhn/tui.editor/blob/253a9a086f5a8ff76a1f7a4be5e104c0b0e44b8c/apps/editor/src/base.ts#L155-L158

Might result in:
```
TypeError: Cannot read properties of undefined (reading 'focus')
    at apply (http://localhost:4200/webpack:/node_modules/@toast-ui/editor/dist/esm/index.js:1540:26)
```
## To Reproduce
1. Destroy the editor by calling editor.destroy() when timers are scheduled. (Maybe calling the destroy one frame after creating it?) 

## Expected behavior
Calling destroy should release all resources including timers to prevent future reference exceptions.

These two examples are just the ones that actually caused exceptions in our project but checking all timers throughout the code might be necessary.

**Comment by js87zz** [comment]
@vendi95 
Oh..I missed it. Thanks for reporting!
