### ISSUE TITLE
CodeBlock starting with two spaces makes editor not editable

### ISSUE THREAD

**Issue by z-950** [nhn/tui.editor#2404]
## Describe the bug
CodeBlock starting with two spaces makes editor not editable.

## To Reproduce
1. Input two " " and two "`"
2. Input one "`"
3. See error

## Expected behavior
Should not have error

## Desktop (please complete the following information):
 - OS: windows 10
 - Browser chrome
 - Version 99.0.4844.82

## Additional context
Editor version: 3.1.3

Error message: 
```
Uncaught TypeError: Cannot read properties of undefined (reading 'nodeSize')
    at Fragment.nodesBetween (toastui-editor-all.js:3498:52)
    at Node.nodesBetween (toastui-editor-all.js:4490:16)
    at Transaction.Transform.addMark (toastui-editor-all.js:8187:12)
    at toastui-editor-all.js:18488:20
    at Array.forEach (<anonymous>)
    at appendMarkTr (toastui-editor-all.js:18470:11)
    at Plugin.appendTransaction (toastui-editor-all.js:18443:17)
    at EditorState.applyTransaction (toastui-editor-all.js:9651:43)
    at EditorView.dispatchTransaction (toastui-editor-all.js:20558:46)
    at EditorView.dispatch (toastui-editor-all.js:14968:50)
```

**Comment by jwlee1108** [comment]
@z-950 I can reproduce it. we'll fix it.

**Comment by EngincanV** [comment]
Any updates?
