### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by guhongjie** [nhn/tui.editor#2461]
× Install fail! Error: [tui-editor@1.4.10 › tui-chart@3.11.3 › raphael@git+https://github.com/nhn/raphael.git#2.2.0-c] An unknown git error occurrere-rte from git squire-rte@github:seonim-ryu/Squire#fd40b4e3020845825701e9689f190bab3f4775d4, may be very slow, please keep patienced                                                                                                                                                  aphael from git raphael@git+https://github.com/nhn/raphael.git#2.2.0-c, may be very slow, please keep patience
Error: [tui-editor@1.4.10 › tui-chart@3.11.3 › raphael@git+https://github.com/nhn/raphael.git#2.2.0-c] An unknown git error occurred               d
    at module.exports (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\download\git.js:36:11)
    at async module.exports (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\download\index.js:17:12)     
    at async _install (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\install.js:125:16)
    at async install (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\install.js:26:12)
    at async mapper (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\install.js:266:9)

**Comment by chengkai2022** [comment]
i find it too，i think it is about address.

**Comment by jwlee1108** [comment]
@guhongjie Can you tell me the Node and NPM versions?

**Comment by kentLin0** [comment]
i find too，my Node version is v14.19.0，npm version is 6.14.17

**Comment by srahul99** [comment]
Still facing same issue
