### ISSUE TITLE
Selecting text within a table sometimes just stops

### ISSUE THREAD

**Issue by Malaber** [nhn/tui.editor#2759]
## Describe the bug
When selecting text within a table, the selection sometimes stops and switches to the whole table cell instead of just the text.

## To Reproduce
Open Firefox
Go to the latest version in TUI Editor demo
( https://ui.toast.com/tui-editor )
In WYSIWYG mode try to select the text in the table, sometimes it will jump to selecting the whole cell.

## Expected behavior
You can select text as much as you want, only selecting the whole cell if you move your mouse out of the text.

## Screenshots
![OFFICIAL_TUI_Editor_highlight_tables_bug](https://user-images.githubusercontent.com/32635600/192979776-1f2030ae-d6e9-45c0-a023-27bd0a0570ed.gif)

![ONE_TUI_Editor_highlight_tables_bug](https://user-images.githubusercontent.com/32635600/192979844-40d3a144-a23d-41cd-bbe1-6105cc2efe2e.gif)
(In our own implementation the selection of table cells currently does not work, so this is why it looks like nothing is selected when the selection switches to the cell)

### Browsers
 - OS: Mac OS 12.6 on M1 MacBook Pro
 - Browser Firefox 105.0 (64-Bit)
 
A colleague of mine has the problem on Windows in Chrome and Firefox as well (i currently don't know the versions)

### TUI Editor
latest version in TUI Editor demo
( https://ui.toast.com/tui-editor )

&

```
"@toast-ui/editor": {
      "version": "3.1.8"
}
```

**Comment by jwlee1108** [comment]
Thank you for the issue. I'll check it.

**Comment by rogerfar** [comment]
This is because the console throws an error:

Try selecting multiple cells in the table and it throws the error:

```
Uncaught TypeError: Class constructor Vt cannot be invoked without 'new'
    at new n (toastui-editor-all.min.js:24:348354)
    at e.setCellSelection (toastui-editor-all.min.js:24:352714)
    at e.handleMousemove (toastui-editor-all.min.js:24:351836)
```

**Comment by reynirf** [comment]
I fixed the issue. I'll write down what I did as I don't have time to create a PR right now.

In webpack.config.js for the editor, add **babel-loader** to the rules and add the plugins listed below to dev dependencies in the package.json for the editor.

I also added "target": "ES2020", to compilerOptions in tsconfig.json

Hope this helps anyone that wants to fork and fix until an official fix comes out.

Also, I'm sure not all of the rules below are required for the fix. It's just what I added.

```
use: [
        {
          loader: 'babel-loader',
          options: {
            presets: [
              '@babel/preset-env',
              '@babel/preset-typescript', // Add this preset for TypeScript support
              '@babel/plugin-proposal-class-properties',
              '@babel/plugin-transform-classes',
            ],
          },
        },
        {
          loader: 'ts-loader',
          options: {
            transpileOnly: true,
          },
        },
      ],
```
