### ISSUE TITLE
Selected table cell's background color is not changed and merge cell option doesn't appear.

### ISSUE THREAD

**Issue by jjungeun** [nhn/tui.editor#3211]
## Summary
I have 3 problems.
1. Selected table cell's background color is not changed
2. Merge cell option doesn't appear even if i added plugin.
3. When select cell, below console error is printed. 
  Is there any way to resolve this problem without node version downgrade to v16?
```
index.js:19093 Uncaught TypeError: Class constructor Selection cannot be invoked without 'new'
    at new CellSelection (index.js:19093:1)
    at TableSelection.setCellSelection (index.js:19429:1)
    at TableSelection.handleMousemove (index.js:19377:1)
```

## Screenshots
https://github.com/nhn/tui.editor/assets/19261711/26929519-14d9-4236-a8ce-b1b8864c0740

## Version
```package.json
{
....
    "@toast-ui/editor": "^3.2.2",
    "@toast-ui/editor-plugin-table-merged-cell": "^3.1.0",
    "@toast-ui/react-editor": "^3.1.7",
    "prosemirror-state": "^1.3.4",
    "prosemirror-transform": "^1.4.2",
}
```
node v19
react v18

## Code
```
import '@toast-ui/editor/dist/toastui-editor.css';
import '@toast-ui/editor-plugin-table-merged-cell/dist/toastui-editor-plugin-table-merged-cell.css';
import { Editor } from '@toast-ui/react-editor';
import React from 'react';
import tableMergedCell from "@toast-ui/editor-plugin-table-merged-cell";

interface AdvancedTextEditorProps {
  ref?: any;
  defaultValue?: string;
  value?: string;
  placeholder?: string;
  onChange?: (event: any) => void;
  readonly?: boolean;
  minHeight?: string;
  maxHeight?: string;
};

export const AdvancedTextEditor: React.FC<AdvancedTextEditorProps> = ({
  ref,
  defaultValue,
  value,
  placeholder,
  onChange,
  readonly,
  minHeight,
  maxHeight
}) => {
  const toolbarOptions = [
    ['heading', 'bold', 'italic', 'strike'],
    ['hr', 'quote'],
    ['ul', 'ol', 'task'],
    ['table', 'image', 'link'],
    ['code', 'codeblock'],
    ['scrollSync']
  ];

  return (
      <Editor
        ref={ref}
        initialValue={defaultValue}
        previewStyle='vertical'
        initialEditType='wysiwyg'
        placeholder={placeholder}
        toolbarItems={toolbarOptions}
        autofocus={false}
        plugins={[tableMergedCell]}
      />
  );
};
```

**Comment by SuperWonjune** [comment]
+1, I have a same problem.

**Comment by qdu123** [comment]
i have the same problem too,but in this page (https://ui.toast.com/tui-editor, With All Plugins section),the plugin works well

**Comment by Morton-Freer** [comment]
我使用V3.2.2版本的编辑器及 V3.1.0版本的ditor-plugin-table-merged-cell插件,在所见即所得模式下,也不能选中表格的单元格并进行合并,抛出上述同样问题;

**Comment by chenkuangkuang** [comment]
install these and saved for me
    "prosemirror-state": "^1.3.4",
    "prosemirror-transform": "^1.4.2",

**Comment by toma315** [comment]
Doesn't work on [API/Examples](https://nhn.github.io/tui.editor/latest/) (Examples) either. As @chenkuangkuang pointed out, the prosemirror dependencies are missing in the distribution. The code being responsible for cell selection is crashing due to the Selection class of prosemirror not being available, thus no cells get selected, thus the table merge cell plugin doesn't see multiple cells selected, thus the merge cell option is not provided.

**Comment by davidm-glitch** [comment]
Ive got the same problem, it seems to work when you lock the version exactly to
```
"prosemirror-state": "1.3.4",
"prosemirror-transform": "1.4.2",
```
