### ISSUE TITLE
Windows installation through npm not working

### ISSUE THREAD

**Issue by marcoXbresciani** [nhn/tui.editor#655]
## Version
Latest

## Test Environment
Windows 10 Pro 64bit, NPM 6.10.2

## Current Behavior
`npm install --save tui-editor` does not install TUI.

```
Microsoft Windows [Versione 10.0.17134.765]
(c) 2018 Microsoft Corporation. Tutti i diritti sono riservati.

C:\Users\mbresciani\Desktop\Programmi\TUI>npm --version
6.10.2

C:\Users\mbresciani\Desktop\Programmi\TUI>npm install --save tui-editor
npm ERR! Error while executing:
npm ERR! C:\Users\mbresciani\AppData\Local\Programs\Git\cmd\git.EXE ls-remote -h -t git://github.com/adobe-webplatform/eve.git
npm ERR!
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 140.82.118.4]: errno=No such file or directory
npm ERR!
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mbresciani\AppData\Roaming\npm-cache\_logs\2019-09-27T10_19_12_968Z-debug.log
```

## Expected Behavior
`npm install --save tui-editor` should install TUI.

**Comment by marcoXbresciani** [comment]
As usual, can't attach things... Copying here the log file written above:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'tui-editor'
1 verbose cli ]
2 info using npm@6.10.2
3 info using node@v12.9.1
4 verbose npm-session 36e2511122e0fbd8
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/tui-editor 1192ms (from cache)
8 silly pacote tag manifest for tui-editor@latest fetched in 1423ms
9 timing stage:loadCurrentTree Completed in 1460ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule tui-editor@1.4.6 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/@types%2fjquery 516ms (from cache)
18 http fetch GET 304 https://registry.npmjs.org/@types%2fcodemirror 537ms (from cache)
19 http fetch GET 304 https://registry.npmjs.org/codemirror 574ms (from cache)
20 silly pacote range manifest for @types/jquery@^3.3.29 fetched in 610ms
21 silly resolveWithNewModule @types/jquery@3.3.31 checking installable status
22 http fetch GET 304 https://registry.npmjs.org/resize-observer-polyfill 602ms (from cache)
23 http fetch GET 304 https://registry.npmjs.org/highlight.js 608ms (from cache)
24 silly pacote version manifest for @types/codemirror@0.0.71 fetched in 650ms
25 silly resolveWithNewModule @types/codemirror@0.0.71 checking installable status
26 http fetch GET 304 https://registry.npmjs.org/jquery 644ms (from cache)
27 silly pacote range manifest for codemirror@^5.33.0 fetched in 677ms
28 silly resolveWithNewModule codemirror@5.49.0 checking installable status
29 silly pacote range manifest for highlight.js@^9.12.0 fetched in 726ms
30 silly resolveWithNewModule highlight.js@9.15.10 checking installable status
31 http fetch GET 304 https://registry.npmjs.org/markdown-it 722ms (from cache)
32 http fetch GET 200 https://registry.npmjs.org/@types%2fmarkdown-it 732ms
33 silly pacote version manifest for @types/markdown-it@0.0.7 fetched in 787ms
34 silly resolveWithNewModule @types/markdown-it@0.0.7 checking installable status
35 silly pacote range manifest for markdown-it@^8.4.0 fetched in 788ms
36 silly resolveWithNewModule markdown-it@8.4.2 checking installable status
37 silly pacote range manifest for resize-observer-polyfill@^1.5.0 fetched in 790ms
38 silly resolveWithNewModule resize-observer-polyfill@1.5.1 checking installable status
39 silly pacote range manifest for jquery@^3.3.1 fetched in 798ms
40 silly resolveWithNewModule jquery@3.4.1 checking installable status
41 http fetch GET 304 https://registry.npmjs.org/plantuml-encoder 1321ms (from cache)
42 silly pacote range manifest for plantuml-encoder@^1.2.5 fetched in 1363ms
43 silly resolveWithNewModule plantuml-encoder@1.4.0 checking installable status
44 http fetch GET 304 https://registry.npmjs.org/tui-chart 918ms (from cache)
45 silly pacote range manifest for tui-chart@^3.7.0 fetched in 960ms
46 silly resolveWithNewModule tui-chart@3.8.0 checking installable status
47 http fetch GET 304 https://registry.npmjs.org/to-mark 1017ms (from cache)
48 http fetch GET 304 https://registry.npmjs.org/tui-code-snippet 954ms (from cache)
49 silly pacote range manifest for tui-code-snippet@^1.5.0 fetched in 982ms
50 silly resolveWithNewModule tui-code-snippet@1.5.2 checking installable status
51 http fetch GET 304 https://registry.npmjs.org/tui-color-picker 952ms (from cache)
52 silly pacote range manifest for to-mark@^1.1.7 fetched in 1074ms
53 silly resolveWithNewModule to-mark@1.1.7 checking installable status
54 silly pacote range manifest for tui-color-picker@^2.2.1 fetched in 975ms
55 silly resolveWithNewModule tui-color-picker@2.2.4 checking installable status
56 silly pacote git manifest for squire-rte@github:seonim-ryu/Squire#fb6cd9b1ac66ca471ded83637523c4fbf7072f86 fetched in 22670ms
57 silly resolveWithNewModule squire-rte@1.9.0 checking installable status
58 http fetch GET 304 https://registry.npmjs.org/@types%2ftern 195ms (from cache)
59 silly pacote range manifest for @types/tern@* fetched in 227ms
60 silly resolveWithNewModule @types/tern@0.23.3 checking installable status
61 http fetch GET 304 https://registry.npmjs.org/@types%2festree 860ms (from cache)
62 silly pacote range manifest for @types/estree@* fetched in 874ms
63 silly resolveWithNewModule @types/estree@0.0.39 checking installable status
64 http fetch GET 304 https://registry.npmjs.org/@types%2fsizzle 61ms (from cache)
65 silly pacote range manifest for @types/sizzle@* fetched in 75ms
66 silly resolveWithNewModule @types/sizzle@2.3.2 checking installable status
67 http fetch GET 304 https://registry.npmjs.org/@types%2flinkify-it 54ms (from cache)
68 silly pacote range manifest for @types/linkify-it@* fetched in 77ms
69 silly resolveWithNewModule @types/linkify-it@2.1.0 checking installable status
70 http fetch GET 304 https://registry.npmjs.org/uc.micro 100ms (from cache)
71 silly pacote range manifest for uc.micro@^1.0.5 fetched in 112ms
72 silly resolveWithNewModule uc.micro@1.0.6 checking installable status
73 http fetch GET 304 https://registry.npmjs.org/mdurl 114ms (from cache)
74 http fetch GET 304 https://registry.npmjs.org/argparse 120ms (from cache)
75 http fetch GET 304 https://registry.npmjs.org/linkify-it 126ms (from cache)
76 silly pacote range manifest for argparse@^1.0.7 fetched in 160ms
77 silly resolveWithNewModule argparse@1.0.10 checking installable status
78 http fetch GET 304 https://registry.npmjs.org/entities 163ms (from cache)
79 silly pacote range manifest for mdurl@^1.0.1 fetched in 169ms
80 silly resolveWithNewModule mdurl@1.0.1 checking installable status
81 silly pacote range manifest for entities@~1.1.1 fetched in 187ms
82 silly resolveWithNewModule entities@1.1.2 checking installable status
83 silly pacote range manifest for linkify-it@^2.0.0 fetched in 211ms
84 silly resolveWithNewModule linkify-it@2.2.0 checking installable status
85 http fetch GET 304 https://registry.npmjs.org/sprintf-js 111ms (from cache)
86 silly pacote range manifest for sprintf-js@~1.0.2 fetched in 146ms
87 silly resolveWithNewModule sprintf-js@1.0.3 checking installable status
88 http fetch GET 304 https://registry.npmjs.org/babel-polyfill 76ms (from cache)
89 silly pacote range manifest for babel-polyfill@^6.26.0 fetched in 90ms
90 silly resolveWithNewModule babel-polyfill@6.26.0 checking installable status
91 silly pacote git manifest for raphael@git+https://github.com/nhn/raphael.git#2.2.0-c fetched in 779ms
92 silly resolveWithNewModule raphael@2.2.0-c checking installable status
93 http fetch GET 304 https://registry.npmjs.org/babel-runtime 98ms (from cache)
94 silly pacote range manifest for babel-runtime@^6.26.0 fetched in 135ms
95 silly resolveWithNewModule babel-runtime@6.26.0 checking installable status
96 http fetch GET 304 https://registry.npmjs.org/regenerator-runtime 154ms (from cache)
97 http fetch GET 304 https://registry.npmjs.org/core-js 170ms (from cache)
98 silly pacote range manifest for regenerator-runtime@^0.10.5 fetched in 197ms
99 silly resolveWithNewModule regenerator-runtime@0.10.5 checking installable status
100 silly pacote range manifest for core-js@^2.5.0 fetched in 206ms
101 silly resolveWithNewModule core-js@2.6.9 checking installable status
102 silly pacote range manifest for regenerator-runtime@^0.11.0 fetched in 20ms
103 silly resolveWithNewModule regenerator-runtime@0.11.1 checking installable status
104 silly fetchPackageMetaData error for eve@git://github.com/adobe-webplatform/eve.git#eef80ed Error while executing:
104 silly fetchPackageMetaData C:\Users\mbresciani\AppData\Local\Programs\Git\cmd\git.EXE ls-remote -h -t git://github.com/adobe-webplatform/eve.git
104 silly fetchPackageMetaData
104 silly fetchPackageMetaData fatal: unable to connect to github.com:
104 silly fetchPackageMetaData github.com[0: 140.82.118.4]: errno=No such file or directory
104 silly fetchPackageMetaData
104 silly fetchPackageMetaData
104 silly fetchPackageMetaData exited with error code: 128
105 timing stage:rollbackFailedOptional Completed in 1ms
106 timing stage:runTopLevelLifecycles Completed in 47904ms
107 silly saveTree TUI
107 silly saveTree `-- tui-editor@1.4.6
107 silly saveTree   +-- @types/codemirror@0.0.71
107 silly saveTree   | `-- @types/tern@0.23.3
107 silly saveTree   |   `-- @types/estree@0.0.39
107 silly saveTree   +-- @types/jquery@3.3.31
107 silly saveTree   | `-- @types/sizzle@2.3.2
107 silly saveTree   +-- @types/markdown-it@0.0.7
107 silly saveTree   | `-- @types/linkify-it@2.1.0
107 silly saveTree   +-- codemirror@5.49.0
107 silly saveTree   +-- highlight.js@9.15.10
107 silly saveTree   +-- jquery@3.4.1
107 silly saveTree   +-- markdown-it@8.4.2
107 silly saveTree   | +-- argparse@1.0.10
107 silly saveTree   | | `-- sprintf-js@1.0.3
107 silly saveTree   | +-- entities@1.1.2
107 silly saveTree   | +-- linkify-it@2.2.0
107 silly saveTree   | | `-- uc.micro@1.0.6
107 silly saveTree   | +-- mdurl@1.0.1
107 silly saveTree   | `-- uc.micro@1.0.6
107 silly saveTree   +-- plantuml-encoder@1.4.0
107 silly saveTree   +-- resize-observer-polyfill@1.5.1
107 silly saveTree   +-- squire-rte@1.9.0
107 silly saveTree   +-- to-mark@1.1.7
107 silly saveTree   +-- tui-chart@3.8.0
107 silly saveTree   | +-- babel-polyfill@6.26.0
107 silly saveTree   | | +-- babel-runtime@6.26.0
107 silly saveTree   | | | +-- core-js@2.6.9
107 silly saveTree   | | | `-- regenerator-runtime@0.11.1
107 silly saveTree   | | +-- core-js@2.6.9
107 silly saveTree   | | `-- regenerator-runtime@0.10.5
107 silly saveTree   | +-- raphael@2.2.0-c
107 silly saveTree   | `-- tui-code-snippet@1.5.2
107 silly saveTree   +-- tui-code-snippet@1.5.2
107 silly saveTree   `-- tui-color-picker@2.2.4
108 verbose stack Error: exited with error code: 128
108 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\util\finished.js:12:19)
108 verbose stack     at ChildProcess.emit (events.js:209:13)
108 verbose stack     at maybeClose (internal/child_process.js:1021:16)
108 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
109 verbose cwd C:\Users\mbresciani\Desktop\Programmi\TUI
110 verbose Windows_NT 10.0.17134
111 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "tui-editor"
112 verbose node v12.9.1
113 verbose npm  v6.10.2
114 error Error while executing:
114 error C:\Users\mbresciani\AppData\Local\Programs\Git\cmd\git.EXE ls-remote -h -t git://github.com/adobe-webplatform/eve.git
114 error
114 error fatal: unable to connect to github.com:
114 error github.com[0: 140.82.118.4]: errno=No such file or directory
114 error
114 error
114 error exited with error code: 128
115 verbose exit [ 1, true ]
```

**Comment by marcoXbresciani** [comment]
Here is the ping:

```

C:\Users\mbresciani\Desktop\Programmi\TUI>ping github.com

Esecuzione di Ping github.com [140.82.118.3] con 32 byte di dati:
Risposta da 140.82.118.3: byte=32 durata=33ms TTL=56
Risposta da 140.82.118.3: byte=32 durata=32ms TTL=56
Risposta da 140.82.118.3: byte=32 durata=32ms TTL=56
Risposta da 140.82.118.3: byte=32 durata=33ms TTL=56

Statistiche Ping per 140.82.118.3:
    Pacchetti: Trasmessi = 4, Ricevuti = 4,
    Persi = 0 (0% persi),
Tempo approssimativo percorsi andata/ritorno in millisecondi:
    Minimo = 32ms, Massimo =  33ms, Medio =  32ms
```

**Comment by seonim-ryu** [comment]
@marcoXbresciani 
Some situations are suspected. Would you like to install it again under the following three conditions?

1. Install after deleting `package-lock.json` file
2. Install `Node.js` in LTS version (Current v10.16.3)
3. Install from [Git Bash](https://gitforwindows.org/) instead of CMD

**Comment by marcoXbresciani** [comment]
Same also from Git Bash.

```
$ npm install --save tui-editor
npm ERR! Error while executing:
npm ERR! C:\Users\mbresciani\AppData\Local\Programs\Git\mingw64\bin\git.EXE ls-remote -h -t git://github.com/adobe-webplatform/eve.git
npm ERR!
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 140.82.118.4]: errno=No such file or directory
npm ERR!
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mbresciani\AppData\Roaming\npm-cache\_logs\2019-10-03T09_18_46_857Z-debug.log
```

I'm gonna try removing node v12.9.1 and installing the LTS.

**Comment by marcoXbresciani** [comment]
Yup. Can't install the LTS... And now I've uninstalled also the current and can't reinstall it.

> The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2755.

:(
